FROM php:8.3-fpm-bookworm

ARG user=agendaapp
ARG uid=1000

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    default-libmysqlclient-dev \
    default-mysql-client \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd sockets

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Install redis
RUN pecl install -o -f redis xdebug \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis xdebug

# Set working directory
WORKDIR /var/www

# Copy custom configurations PHP
COPY docker/php/custom.ini /usr/local/etc/php/conf.d/custom.ini

# Copiar composer.json e composer.lock primeiro (para cache)
COPY composer.json composer.lock /var/www/

# Copia os arquivos do projeto
COPY . /var/www

# Instalar dependências PHP
RUN composer install --optimize-autoloader --no-interaction --prefer-dist

# Ajusta permissões
RUN chown -R $user:www-data /var/www/storage /var/www/bootstrap/cache
RUN chmod -R g+w /var/www/storage /var/www/bootstrap/cache
RUN chown -R $user:$user /var/www

USER $user

EXPOSE 9000